### ISSUE TITLE
集成 aspectjx 失败问题

### ISSUE THREAD

**Issue by mumu1244868** [wurensen/gradle_plugin_android_aspectjx#10]
你好，按照流程集成了aspectjx，可是就是无法实现aop，能问问是否因为AndroidStudio版本问题吗
这是我的AS版本

Android Studio Arctic Fox | 2020.3.1 Patch 1
Build #AI-203.7717.56.2031.7621141, built on August 8, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2560M
Cores: 12
Registry: external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: DBN, GsonFormatPlus, com.codota.csp.intellij, com.duke.screenmatch, com.yiycf.plugins.mavenDependencyHelper, de.netnexus.camelcaseplugin, leetcode-editor, mobi.hsz.idea.gitignore, wu.seal.tool.jsontokotlin, com.developerphil.adbidea, com.idescout.sqlite, cn.yiiguxing.plugin.translate, izhangzhihao.rainbow.brackets, org.intellij.plugins.markdown

**Comment by wurensen** [comment]
贴下接入代码，还有插件相关配置，建议先把aspectjx{}中的所有过滤规则都去掉，然后构建看下有没有正确织入。

**Comment by mumu1244868** [comment]
用了你的2.0.14版本已经可以了   谢谢
