### ISSUE TITLE
Execution failed for task ':app:transformClassesWithAjxForDebug'

### ISSUE THREAD

**Issue by ytrug1224** [wurensen/gradle_plugin_android_aspectjx#11]
Execution failed for task ':app:transformClassesWithAjxForDebug'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Mismatch when building parameterization map. For type 'Pkotlin/jvm/functions/Function3<Pkotlinx/coroutines/flow/FlowCollector<-Ljava/lang/Object;>;Ljava/lang/Object;Lkotlin/Unit;>;' expecting 4:[P1 P2 P3 R] type parameters but found 3:[Pkotlinx/coroutines/flow/FlowCollector<-Ljava/lang/Object;>; Ljava/lang/Object; Lkotlin/Unit;]

**Comment by wurensen** [comment]
可添加如下配置：

// 移除kotlin相关，编译错误和提升速度
exclude 'kotlin.jvm', 'kotlin.internal'
exclude 'kotlinx.coroutines.internal', 'kotlinx.coroutines.android'
