### ISSUE TITLE
是否不能织入library moudle中带代码？

### ISSUE THREAD

**Issue by po1xiao** [wurensen/gradle_plugin_android_aspectjx#16]
把代码放到library中，然后在app moudle中引用是无法织入成功的，放到app module就可以。

**Comment by wurensen** [comment]
@po1xiao 描述下是什么放到library module中，织入规则类吗还是其它？还有，注意下library有没有会类似于apt生成代码的，然后刚好被你的exclude规则给过滤掉了，比如glide，你在library写相关类，自动生成的代码是以glide的包名，然后你又exclude掉glide相关，结果会出现你整个library module都被忽略处理。

**Comment by wurensen** [comment]
补充一点，所有的library module在transform处理的时候，都是以jar作为输入的，所以其中一个类匹配上exclude规则，整个jar都会被忽略处理。你可以先到app/build/intermediates/transforms/ajx/debug/__content__.json，来查看你没有被处理到的module是哪一个jar，然后到app/build/intermediates/ajx/debug/includeJars.json查看这个jar是否存在，不存在就表示被exclude掉忽略处理了。

**Comment by po1xiao** [comment]
其实我不太了解织入规则类具体代表的什么（第一次用这个），经过排查和重新测试，我重新把需要织入需要编写的相关代码写到的了library module中，是可以在app module和其它library module中织入的，至于之前为什么没能成功，因为之前我是用HujiangTechnology的依赖做的测试，有可能是这个原因引起的，也有可能是因为我代码写的有问题。

这个Issue我就先关了，感谢您的解答。
