### ISSUE TITLE
java.util.concurrent.ExecutionException: java.io.IOExcepti on: File 'xxx\app\build\intermediates\transforms\APMSPlugin\debug\125\com\xxx\xxx\tracker' exists but is a directory

### ISSUE THREAD

**Issue by wlssing** [wurensen/gradle_plugin_android_aspectjx#19]
java.util.concurrent.ExecutionException: java.io.IOExcepti
on: File 'xxx\app\build\intermediates\transforms\APMSPlugin\debug\125\com\xxx\xxx\tracker' exists but is a directory
 有这个报错

**Comment by wurensen** [comment]
@wlssing 提供下更详细的错误信息，如果是这个插件织入错误，会有错误日志在build/outputs/logs/下面

**Comment by wurensen** [comment]
@wlssing 这个APMSPlugin应该是上一个处理的transform，确认下APMSPlugin这个插件处理是不是有问题。
