### ISSUE TITLE
AJXCache适配AppBundle

### ISSUE THREAD

**Issue by FortuneDream** [wurensen/gradle_plugin_android_aspectjx#3]
目前貌似仍然没有适配AppBundle，会出现
 Attribute activity#xxxxx.SearchActivity@splitName value=(dfm_live) from [:ks-dynamic-features:dfm_live] AndroidManifest.xml:404:13-41
        is also present at [:ks-dynamic-features:magic_sdk] AndroidManifest.xml:354:13-42 value=(magic_sdk).
        Suggestion: add 'tools:replace="android:splitName"' to <activity> element at AndroidManifest.xml:10:9-15:88 to override.
这个问题是在Task：processGooglePerfManifest，也就是多Flavor的情况下，还没有执行到Transform阶段。
我把AJXTransform构造函数中的ajxCache=new AJXCache(proj)，注释了之后，就可以顺利通过此Task。
所以这个AJXCache的内部实现仍然有问题。

**Comment by wurensen** [comment]
@FortuneDream 你可以用新版本2.0.15试试，加了各种android plugin的支持。

**Comment by wurensen** [comment]
@FortuneDream 测试了下，appBundle执行没有问题，你用最新版本看下能不能复现，我先关掉了。
