### ISSUE TITLE
Transforms with scopes '[SUB_PROJECTS, EXTERNAL_LIBRARIES]' cannot be applied to library projects.

### ISSUE THREAD

**Issue by jiqianwen** [wurensen/gradle_plugin_android_aspectjx#30]
升级3.0.0就报错了，请问这个该怎么修改呢？

**Comment by gnmmdk** [comment]
同问，如何解决？

**Comment by jiqianwen** [comment]
> 同问，如何解决？

我降级回2.0.14版本了，3.0.0得用AS新版插件的方式引入才行吧

**Comment by wurensen** [comment]
@jiqianwen 3.0.0开始两种插件引入方式都支持

**Comment by jiqianwen** [comment]
> @jiqianwen 3.0.0开始两种插件引入方式都支持

但是升级之后，确实会报标题的错误，用不了，这是咋回事呢

**Comment by wurensen** [comment]
@jiqianwen 插件旧版本没有问题吗？看报错旧版本应该也有问题。你是只升级该插件，也升级AGP了吗？因为这个报错是AGP那边的检查，不排除是AGP新版本才加的。

**Comment by gnmmdk** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip

classpath 'com.android.tools.build:gradle:7.2.2'

这是我的环境，并且application和library都有使用

**Comment by jiqianwen** [comment]
> distributionUrl=https://services.gradle.org/distributions/gradle-7.3.3-all.zip
> 
> classpath 'com.android.tools.build:gradle:7.2.2'
> 
> 这是我的环境，并且application和library都有使用

我也是同样的版本，依旧报这个错

**Comment by wurensen** [comment]
@gnmmdk @jiqianwen module支持需要再等几天，因为之前作者还有个历史bug没去修，导致增量编译场景下，织入规则类来自于jar（module在编译时也是被当成jar给app处理）被删除时，不能正确删除。
我这边应该会改方案，所以要耽搁几天了。

**Comment by jiqianwen** [comment]
> @gnmmdk @jiqianwen module支持需要再等几天，因为之前作者还有个历史bug没去修，导致增量编译场景下，织入规则类来自于jar（module在编译时也是被当成jar给app处理）被删除时，不能正确增量编译，可能导致运行时找不到类。 我这边应该会改方案，所以要耽搁几天了。

好的，辛苦了，感谢

**Comment by keekkenen** [comment]
> 这是我的环境，并且application和library都有使用

In my case I  use application with few library modules. I tested 3.0.0 version plugin in was correct work, but at first run I had the same error, but agter I apply it plugin for application module only, and it fixed error. I checked my aspects it was work correctly. In total I desided what plugin has strange bihavior and return to old version based on 2.0.14.

**Comment by wurensen** [comment]
@keekkenen The new version will be published soon.

**Comment by keekkenen** [comment]
> The new version will be published soon.

Ok, no problem, but fixed 2.0.14 version correct work in my case (app + library modules) with Gradle 7.3.3 and AGP 7.2.2

**Comment by gnmmdk** [comment]
> 
十分感谢🙏。
不知道你们大概需要多久时间，现在一些应用市场需要支持android13，连带着Gradle需要升级，所以该库也需要升级。

**Comment by gnmmdk** [comment]
【重要】关于Android13适配工作推进的通知
尊敬的开发者：

您好！

随着Android 13正式版发布，小米将于2022年10月起逐步开放部分机型升级至Andorid-T(安卓13）版本。为提升Android应用性能体验，小米将持续推进Android 13适配工作，具体如下：

2022年10月8日起，小米开发者站将会具备Android 13自动化检测能力，开发者在应用新增、更新时，上传应用后会自动进行兼容性测试，若应用未通过检测，我们会以邮件的方式通知您。同时，针对未更新的应用，我们也会于10月内进行一次全库自动化检测扫描。

11月14日起，我们将根据开发者的配合情况，针对未适配Android 13的应用，在应用商店内和安装器环节增加用户侧提醒，告知应用未适配的问题。

12月1日起，未适配Android 13的应用将无法发布到小米应用商店且无法更新版本。

小米将全程提供适配支持和服务，包括但不限于自动化检测能力、适配指引文档等。如有其他疑问，您可点击[在线工单](https://www.sobot.com/chat/pc/v2/index.html?sysnum=5d7e332c4f994cf295cbfb0e81851038)联系我们。

文档链接：

Android 13应用适配指南：https://dev.mi.com/console/doc/detail?pId=2632

Android 13适配资源支持：https://dev.mi.com/console/doc/detail?pId=2745

感谢您的配合！

小米应用商店

2022年9月27日

**Comment by wurensen** [comment]
@gnmmdk 修复连带着重构了，在自测，但新方案耗时增加，可能还要再调整方案。

**Comment by wurensen** [comment]
@keekkenen @gnmmdk @jiqianwen 3.2.0已发布，重构了代码，实现逻辑也重写了，有什么问题及时沟通。

**Comment by jiqianwen** [comment]
> @keekkenen @gnmmdk @jiqianwen 3.2.0已发布，重构了代码，实现逻辑也重写了，有什么问题及时沟通。

辛苦了，感谢
