### ISSUE TITLE
Configuration cache state could not be cached: input property '$3'

### ISSUE THREAD

**Issue by fail572872916** [wurensen/gradle_plugin_android_aspectjx#32]
具体报错如下：
Configuration cache state could not be cached: input property '$3' of ':app:transformClassesWithAjxForDebug': error writing value of type 'org.gradle.api.internal.file.FilteredFileTree'
> Querying the mapped value of provider(interface java.util.Set) before task ':app:compileDebugKotlin' has completed is not supported

原因：我在gradle.properties中增加了如下配置   org.gradle.unsafe.configuration-cache=true
当我注释掉它的时候，工作正常 

我的环境如下  Android Studio Chipmunk | 2021.2.1 Patch 2

plugins {
    id("com.android.application") version "7.1.3" apply false
    id("com.android.library") version "7.1.3" apply false
    id("org.jetbrains.kotlin.android") version "1.6.21" apply false
    id("io.github.wurensen.android-aspectjx") version "3.0.0"  apply false
}
您甚至不用进行配置，仅   在gradle.properties中增加如下配置   org.gradle.unsafe.configuration-cache=true  即可
我提供一个代码仓库， 它的地址是  https://github.com/fail572872916/testaop

**Comment by wurensen** [comment]
@fail572872916 我本地已经修改验证，但是gradle需要升级到最新版本7.5.1才能正常，否则有异常。
