### ISSUE TITLE
提示：Transforms with scopes '[SUB_PROJECTS, EXTERNAL_LIBRARIES]' cannot be applied to library projects.

### ISSUE THREAD

**Issue by gnmmdk** [wurensen/gradle_plugin_android_aspectjx#34]
![image](https://user-images.githubusercontent.com/18391426/190340604-04d91f66-4c7c-4531-bbcd-75f09a18323b.png)

**Comment by wurensen** [comment]
@gnmmdk 你是在library模块引入的吗？可以先改到app模块试试

**Comment by gnmmdk** [comment]
> 
是的，不行啊，我们项目library都需要引入。

**Comment by keekkenen** [comment]
why 3.1.0 version doesn't wotk with library ?

**Comment by keekkenen** [comment]
> why 3.1.0 version doesn't work with library ? apply plugin: 'com.android.library' apply plugin: 'io.github.wurensen.android-aspectjx'

mm.. I understood, plugin see all libraries (libs like a subprojects  - like as part of application) through app and apply aspects for it

**Comment by wurensen** [comment]
@gnmmdk 能描述以下你们使用的场景吗？是app和library都需要分别引入该插件吗？

**Comment by wurensen** [comment]
#30

**Comment by gnmmdk** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip

classpath 'com.android.tools.build:gradle:7.2.2'

这是我的环境，并且application和library都有使用

**Comment by wurensen** [comment]
@gnmmdk 
你们application和library分别都引入插件，是期望application处理所有class，library只处理自己模块的class（library也无法处理第三方依赖类）是吗？
也就是说，@Aspect声明的织入类，只有在该类对应的app/module有引入到该插件才产生作用，对于在module中声明了@Aspect类，但只在app module引入该插件，那这种情况下该织入类就不生效了。
总结就是：织入类的作用范围和引入插件的模块是一致的。
按照以上说明的方式来修改，是符合使用者预期的吧？

**Comment by wurensen** [comment]
> > why 3.1.0 version doesn't work with library ? apply plugin: 'com.android.library' apply plugin: 'io.github.wurensen.android-aspectjx'
> 
> mm.. I understood, plugin see all libraries (libs like a subprojects - like as part of application) through app and apply aspects for it

@gnmmdk I'm sorry about that working library with error right now.  I need to confirm the scope of the class with '@Aspect' when 'application' and 'library' apply the plugin at the same time.

**Comment by wurensen** [comment]
duplicate #30

**Comment by gnmmdk** [comment]
以前使用 HujiangTechnology/gradle_plugin_android_aspectjx，模块是支持使用的，现在升级gradle，所以只能使用到你这个。我们的项目不希望去更改用法。
