### ISSUE TITLE
小白疑惑：和沪江的AspectJ版本使用方式都一样吧？

### ISSUE THREAD

**Issue by Silence-v** [wurensen/gradle_plugin_android_aspectjx#38]
请问和沪江的AspectJ版本使用方式是一样的么，，还没看Demo 
（困在huangjiang-aspectj & Gradle 7.3.3上各种报错，裂开，，，）

**Comment by wurensen** [comment]
@Silence-v 说明文档上有说明，请先阅读一下哈。
