### ISSUE TITLE
[Error]

### ISSUE THREAD

**Issue by jiahl0910** [wurensen/gradle_plugin_android_aspectjx#63]
请提供构建环境相关信息：
- 当前使用的插件版本：
- AGP（Android Gradle Plugin）版本：3.5.4
- Gradle版本：5.4.1
用的版本是：com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.8
报错：
java.lang.RuntimeException: Unable to instantiate application

我这个版本用你的哪个版本可以使用

**Comment by wurensen** [comment]
@jiahl0910 看下说明文档和版本日志啊。

**Comment by jiahl0910** [comment]
> @jiahl0910 看下说明文档和版本日志啊。

看了你的版本，最低是2.0.11。需要Gradle版本为5.6.4，可是我们项目目前升不了；咨询大神这个怎么解决呀

**Comment by wurensen** [comment]
@jiahl0910 我建议你fork过去，自己进行下gradle的适配，我这边只能同时维护两个gradle大版本。
