### ISSUE TITLE
【include使用方法】求指点

### ISSUE THREAD

**Issue by cxMax** [wurensen/gradle_plugin_android_aspectjx#67]
描述：我们android工程十几年老项目，想使用include关键字，就仅仅织入需要配置的java类，而不用全部扫描所有代码织入，请问可以吗？
目前配置如下

aspectjx {
    // 是否debug，开启后会输出织入信息等相关日志（3.3.0版本新增）
    debug = true
    // 是否启动
    enabled = true
    // 指定织入class
  include 'com.demo.apsectj.A'
  include 'com.demo.apsectj.B'
  include 'com.demo.apsectj.C'
  // 排除所有package路径中包含`android.support`的class文件及库（jar文件）
    exclude 'android.support'
    // 排除kotlin
    exclude 'kotlin.jvm', 'kotlin.internal'
    exclude 'kotlinx.coroutines.internal', 'kotlinx.coroutines.android'
}

include， 意思就是 项目app module，就仅仅织入在这里配置的有A.java，B.java，C.java这三个类， 其他类不织入， 主要是想提升编译速度， 不然太慢了

**Comment by cxMax** [comment]
我照着文档看了下，app/build/tmp/transformClassesWithAjxForDebug下，input 和 output都是我上面include指定的文件。

但我有个问题，为什么app/build/intermediates/transforms/ajx/debug下，会有项目中所有类的class。

意思是，编译过程中，还是所有的类都扫了一遍吗？ 主要问这个问题目的，还是跟编译速度有关系，是否我在aspecj配置了要织入的类，编译速度就会大大提升。 而不会去扫一遍所有的项目工程代码

**Comment by cxMax** [comment]
[:app:transformClassesWithAjxForDebug]: DoAspectProcedure finish.[9481ms]
[:app:transformClassesWithAjxForDebug]: close all open jar files: count=1342.[1ms]
[:app:transformClassesWithAjxForDebug]: transform finish.[11496ms]

这个表示织入的所有时间吗

**Comment by wurensen** [comment]
> 我照着文档看了下，app/build/tmp/transformClassesWithAjxForDebug下，input 和 output都是我上面include指定的文件。
> 
> 但我有个问题，为什么app/build/intermediates/transforms/ajx/debug下，会有项目中所有类的class。
> 
> 意思是，编译过程中，还是所有的类都扫了一遍吗？ 主要问这个问题目的，还是跟编译速度有关系，是否我在aspecj配置了要织入的类，编译速度就会大大提升。 而不会去扫一遍所有的项目工程代码

transforms下需要输出当前处理节点的所有结果，这是因为设计机制就是链式的处理，上一个节点的输出是下一个节点的输入；所以，在处理时，对于所有输入文件而言，不需要修改的字节码文件也需要拷贝。

**Comment by wurensen** [comment]
> [:app:transformClassesWithAjxForDebug]: DoAspectProcedure finish.[9481ms] [:app:transformClassesWithAjxForDebug]: close all open jar files: count=1342.[1ms] [:app:transformClassesWithAjxForDebug]: transform finish.[11496ms]
> 
> 这个表示织入的所有时间吗

这个表示的是整个transform处理的时间，包括需要处理的文件进行织入，不需要处理的文件进行拷贝。

**Comment by wurensen** [comment]
include和exclude的判断逻辑是：符合include且不符合exclude，对于依赖库，都是用jar包路径用于判断。
比如你这边：include 'com.demo.apsectj.A'，表示所有class路径有包含这个字符串的（如 'com.demo.apsectj.A.class'或'com.demo.apsectj.AB.class’），都算符合include这条规则。

**Comment by unhoo28** [comment]
> include和exclude的判断逻辑是：符合include且不符合exclude，对于依赖库，都是用jar包路径用于判断。 比如你这边：include 'com.demo.apsectj.A'，表示所有class路径有包含这个字符串的（如 'com.demo.apsectj.A.class'或'com.demo.apsectj.AB.class’），都算符合include这条规则。

你好，如果我只想织入com.demo.A是否只需要添加include 'com.demo.A'而不用添加exclude规则

**Comment by wurensen** [comment]
> > include和exclude的判断逻辑是：符合include且不符合exclude，对于依赖库，都是用jar包路径用于判断。 比如你这边：include 'com.demo.apsectj.A'，表示所有class路径有包含这个字符串的（如 'com.demo.apsectj.A.class'或'com.demo.apsectj.AB.class’），都算符合include这条规则。
> 
> 你好，如果我只想织入com.demo.A是否只需要添加include 'com.demo.A'而不用添加exclude规则

是的

**Comment by cxMax** [comment]
好的 谢谢 明白了
