### ISSUE TITLE
aspectjx会入侵所有的三方包，那是否可以使用include控制到只在本应用的包名下的类生效？而不去第三方sdk包？

### ISSUE THREAD

**Issue by feifanmeng** [wurensen/gradle_plugin_android_aspectjx#8]
aspectjx会入侵所有的三方包，那是否可以使用include控制到只在本应用的包名下的类生效？而不去第三方sdk包？

**Comment by wurensen** [comment]
可以的，但是你要确保你include规则的包名不会恰巧命中第三方sdk，建议所有的规则尽可能详细，防止误include/exclude。
