### ISSUE TITLE
ProceedingJoinPoint.proceed()报错

### ISSUE THREAD

**Issue by fuchengxin** [wurensen/gradle_plugin_android_aspectjx#81]
![image](https://github.com/wurensen/gradle_plugin_android_aspectjx/assets/15795966/225de56a-4f91-4581-8760-3bd5880f2add)
![image](https://github.com/wurensen/gradle_plugin_android_aspectjx/assets/15795966/4d198f01-3922-44f0-aba9-52cff36f2a72)

版本3.3.2，这是使用aop做的权限拦截注解，但是第一次点击的时候 注解确实生效了，也进了权限请求，但是使用 joinPoint.proceed();之后抛异常了，并没有继续走原方法，然后第二次点击就正常了，这个是什么原因

**Comment by fuchengxin** [comment]
> ![image](https://user-images.githubusercontent.com/15795966/284178873-225de56a-4f91-4581-8760-3bd5880f2add.png) ![image](https://user-images.githubusercontent.com/15795966/284179956-4d198f01-3922-44f0-aba9-52cff36f2a72.png)
> 
> 版本3.3.2，这是使用aop做的权限拦截注解，但是第一次点击的时候 注解确实生效了，也进了权限请求，但是使用 joinPoint.proceed();之后抛异常了，并没有继续走原方法，然后第二次点击就正常了，这个是什么原因

这就会导致使用的时候，第一次点击权限申请，然后接受了就没反应了，必须点第二次才能正常的走后面的逻辑

**Comment by wurensen** [comment]
@fuchengxin 看下是不是和这个一样的问题： #60

**Comment by fuchengxin** [comment]
> @fuchengxin 看下是不是和这个一样的问题： #60

确实是这个原因，我一个方法写了2个注解。。。
