### ISSUE TITLE
Unable to instantiate application 

### ISSUE THREAD

**Issue by AnShiHui** [wurensen/gradle_plugin_android_aspectjx#9]
![image](https://user-images.githubusercontent.com/31883020/142578387-b79f1799-abb4-4093-8042-c68e72e1fd35.png)
集成之后启动App报这个错，去掉之后就好了，求解

**Comment by wurensen** [comment]
有接入multidex吗？有的话记得exclude掉：

>    // 排出multidex，防止织入代码后会出现5.0以下执行multidex加载类，但是对应类却不在main dex导致崩溃问题
>   exclude 'androidx.multidex'

**Comment by AnShiHui** [comment]
exclude了还是不行

**Comment by wurensen** [comment]
@AnShiHui 那你得自己排查一下了，直接看看最终apk中的代码。
